export const config = {
  name: "LUCY",
  ticker: "$LUCY",
  description: "Justice for Lucy. A voice for the voiceless.",
  tagline: "She survived. We stand with her.",
  image: "/LUCY.jpg",
  ca: "7eALPwTFrgSVRpYNxTzt59a5sz1dP29FgemNmQhXpump",
  buyLink: "https://pump.fun/coin/7eALPwTFrgSVRpYNxTzt59a5sz1dP29FgemNmQhXpump",
  twitterHandle: "lucypalestine",
  communityLink: "https://x.com/i/communities/2030294008249930003",
  instagramHandle: "sana_aljamal82",
  instagramPostId: "DYYTMc0TSWV",
  supply: "1,000,000,000",
  tax: "0/0",
  launched: false,
}